Repository AIforDevs/website, pull requests merged in 2023-10, with the labels that each got.

#3 updated twitter icon
  index.html
  styles.css
Labels: enhancement, hacktoberfest

#4 Update README.md
  README.md
Labels: hacktoberfest

#6 feat: Added a hover effect to make the features pop up
  styles.css
Labels: hacktoberfest, hactoberfest-accepted

#9 Created the resource page
  index.html
  resources.html
  resources/ai1.jpg
  resources/ai2.jpg
  resources/ai3.jpg
  script.js
  styles_resources.css
Labels: hacktoberfest, hacktoberfest-accepted

#8 feat: added working dark-mode button
  index.html
  styles.css
Labels: hacktoberfest-accepted

#16 Fixed the cta buttons display on mobile screen
  index.html
  styles.css
Labels: hacktoberfest-accepted
